'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MRA_FE_0032

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''TXT_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_ID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TXT_PRODUCT_NM_ON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PRODUCT_NM_ON As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TXT_PRODUCT_NM_OFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PRODUCT_NM_OFF As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''LIST_MENU_CHOSEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIST_MENU_CHOSEN As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''TXT_PRICE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PRICE As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''DDL_TAX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_TAX As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''TXT_PATH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PATH As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''DDL_STS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_STS As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''TXT_NOTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_NOTE As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BTN_ADD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_ADD As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''BTN_UPDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_UPDATE As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''BTN_DELETE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_DELETE As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
