'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MRA_FE_0022

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DDL_MENU_NM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_MENU_NM As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''TXT_PRODUCT_LIST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PRODUCT_LIST As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''TXT_PRODUCT_CHOSEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PRODUCT_CHOSEN As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''BTN_ADD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_ADD As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''BTN_UPDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_UPDATE As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''BTN_DELETE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_DELETE As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
