'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MRA_FE_0041

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''TXT_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_SEARCH As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BTN_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_SEARCH As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''DATE_FROM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DATE_FROM As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''DATE_TO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DATE_TO As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''TIME_FROM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TIME_FROM As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''TIME_TO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TIME_TO As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''BTN_CSV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_CSV As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''GRD_DATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GRD_DATA As Global.System.Web.UI.WebControls.GridView
End Class
