'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MRA_FE_0022

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''IMG_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMG_ID As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBL_MENU_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_MENU_ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXT_NAME_VN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_NAME_VN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_NAME_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_NAME_JP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_NOTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBL_FILEPATH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_FILEPATH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TXT_FILEPATH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_FILEPATH As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''BTN_UPLOAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_UPLOAD As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SELECT_SEND_PRODUCT_LEFT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SELECT_SEND_PRODUCT_LEFT As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''BTN_ADD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_ADD As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTN_UPDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_UPDATE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTN_DELETE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_DELETE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TXT_PATH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PATH As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
